name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: fly-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installe l’outil flyctl
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # (Optionnel) Vérifier la config
      - name: Validate Fly config
        run: flyctl config validate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Déploiement
      - name: Deploy
        run: |
          flyctl deploy \
            --remote-only \
            --app pointage-internet-webapp \
            --strategy immediate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
