name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]   # déploiement automatique à chaque push sur main
  workflow_dispatch: {}     # possibilité de lancer manuellement depuis l’onglet Actions

permissions:
  contents: read

concurrency:
  group: fly-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy app to Fly.io
        run: |
          flyctl deploy --remote-only --app pointage-internet-webapp --strategy immediate
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
